"use client";

import { useState } from 'react';
import { useSession } from 'next-auth/react';
import { HelpCircle, BookOpen, MessageCircle, FileText, Search, ChevronRight, Video, Mail, PhoneCall } from 'lucide-react';

export default function HelpPage() {
  const { data: session } = useSession();
  const userRole = session?.user?.role || 'STAFF';
  const isParent = userRole === 'PARENT';
  const isStudent = userRole === 'STUDENT';

  const [searchQuery, setSearchQuery] = useState('');

  const adminFaqs = [
    {
      category: 'Admissions & Students',
      items: [
        { q: 'How do I generate a new Student ID?', a: 'Student IDs (e.g. DIT/STU/001) are automatically generated by the system when you complete the Admissions form.' },
        { q: 'How do I assign a student to a class?', a: 'Go to Students Directory > click the 3 dots next to a student > Assign Class.' },
        { q: 'How do I link a parent to a student?', a: 'Go to Students Directory > click the 3 dots next to a student > Link Parent/Guardian. The parent profile is created automatically.' }
      ]
    },
    {
      category: 'Grading & Broadsheet',
      items: [
        { q: 'Why is a student missing from the Broadsheet?', a: 'A student will only appear in the Broadsheet if they have been assigned to the specific class you selected in the dropdown.' },
        { q: 'How do I change the CA and Exam weighting?', a: 'Go to Assessment Format in the sidebar. Ensure your new weights total exactly 100% before saving.' },
        { q: 'How do I print a Report Sheet?', a: 'Go to Classes > View Class > Results Tab > Open Broadsheet. Click on any student row to view their summary, then click "View Reportsheet" and hit the Print button.' }
      ]
    },
    {
      category: 'CBT & Examinations',
      items: [
        { q: 'How do I use the Bulk Upload for CBT?', a: 'Format your questions in a text editor separating options with a pipe symbol (|). Example: What is 2+2? | 3 | 4 | 5 | 6 | B | 1.0' },
        { q: 'How do I hide an Internal Exam from students?', a: 'On the Internal Exams page, click the Active/Hidden toggle on the exam card. Hidden exams will not appear in the student portal.' },
        { q: 'How do I use Math Symbols?', a: 'When adding a single question, use the Symbol Toolbar directly below the question text area to insert roots, powers, and fractions.' }
      ]
    }
  ];

  const parentFaqs = [
    {
      category: 'Parent Portal & Navigation',
      items: [
        { q: 'How do I check my child\'s results?', a: 'Go to the "My Children" tab and click the "View Academic Results" button next to your child\'s name.' },
        { q: 'Where can I find the school timetable?', a: 'Click on "School Calendar" in the sidebar to view the active timetable for your child\'s class.' },
      ]
    },
    {
      category: 'Fee Payments',
      items: [
        { q: 'How do I pay school fees?', a: 'Navigate to "Fee Payments". Pending invoices will appear there. Click on the invoice to process securely via online payment.' },
        { q: 'Why is my payment showing as Overdue?', a: 'Invoices that have passed their set due date will automatically be flagged as Overdue. Please settle them immediately to avoid interruption.' },
      ]
    }
  ];

  const faqs = isParent ? parentFaqs : adminFaqs;

  return (
    <div className="space-y-6 max-w-5xl mx-auto pb-32">
      
      {/* Header */}
      <div className="bg-[#0A192F] rounded-3xl p-8 md:p-12 text-center relative overflow-hidden shadow-lg">
        <div className="absolute top-0 right-0 w-64 h-64 bg-[#0033A0] rounded-full blur-3xl opacity-50 -mr-20 -mt-20"></div>
        <div className="absolute bottom-0 left-0 w-64 h-64 bg-[#FFD700] rounded-full blur-3xl opacity-10 -ml-20 -mb-20"></div>
        
        <div className="relative z-10">
          <HelpCircle className="w-12 h-12 text-[#FFD700] mx-auto mb-4" />
          <h1 className="text-3xl md:text-4xl font-black text-white tracking-tight mb-4">How can we help you today?</h1>
          
          <div className="max-w-2xl mx-auto relative">
            <Search className="w-5 h-5 absolute left-4 top-1/2 -translate-y-1/2 text-slate-400" />
            <input 
              type="text" 
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              placeholder="Search for guides, tutorials, or FAQs..." 
              className="w-full pl-12 pr-4 py-4 bg-white/10 border border-white/20 rounded-xl text-white placeholder:text-white/50 focus:bg-white focus:text-slate-900 focus:placeholder:text-slate-400 outline-none transition-all font-medium backdrop-blur-sm"
            />
          </div>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8 pt-4">
        
        {/* LEFT COL: Quick Links & Support */}
        <div className="space-y-6">
          <div className="bg-white rounded-2xl border border-slate-200 shadow-sm p-6">
            <h3 className="font-bold text-slate-900 text-lg mb-4">Quick Guides</h3>
            <div className="space-y-3">
              <button className="w-full flex items-center justify-between p-3 rounded-xl hover:bg-slate-50 border border-transparent hover:border-slate-200 transition-colors group text-left">
                <div className="flex items-center gap-3">
                  <div className="p-2 bg-blue-50 text-[#0033A0] rounded-lg group-hover:bg-[#0033A0] group-hover:text-white transition-colors"><BookOpen className="w-4 h-4" /></div>
                  <span className="font-medium text-slate-700">{isParent ? "Parent Guide" : "Admin Onboarding"}</span>
                </div>
                <ChevronRight className="w-4 h-4 text-slate-300 group-hover:text-[#0033A0]" />
              </button>
              <button className="w-full flex items-center justify-between p-3 rounded-xl hover:bg-slate-50 border border-transparent hover:border-slate-200 transition-colors group text-left">
                <div className="flex items-center gap-3">
                  <div className="p-2 bg-emerald-50 text-emerald-600 rounded-lg group-hover:bg-emerald-600 group-hover:text-white transition-colors"><Video className="w-4 h-4" /></div>
                  <span className="font-medium text-slate-700">Video Tutorials</span>
                </div>
                <ChevronRight className="w-4 h-4 text-slate-300 group-hover:text-emerald-600" />
              </button>
              <button className="w-full flex items-center justify-between p-3 rounded-xl hover:bg-slate-50 border border-transparent hover:border-slate-200 transition-colors group text-left">
                <div className="flex items-center gap-3">
                  <div className="p-2 bg-purple-50 text-purple-600 rounded-lg group-hover:bg-purple-600 group-hover:text-white transition-colors"><FileText className="w-4 h-4" /></div>
                  <span className="font-medium text-slate-700">System Documentation</span>
                </div>
                <ChevronRight className="w-4 h-4 text-slate-300 group-hover:text-purple-600" />
              </button>
            </div>
          </div>

          <div className="bg-gradient-to-br from-slate-900 to-slate-800 rounded-2xl border border-slate-700 shadow-md p-6 text-white relative overflow-hidden">
            <div className="absolute top-0 right-0 p-4 opacity-10"><MessageCircle className="w-24 h-24" /></div>
            <h3 className="font-bold text-lg mb-2 relative z-10">Need technical support?</h3>
            <p className="text-slate-300 text-sm mb-6 relative z-10 leading-relaxed">Our engineering team is available to help resolve any critical system issues or bugs.</p>
            
            <div className="space-y-3 relative z-10">
              <a href="mailto:support@ditmur.com" className="flex items-center gap-3 bg-white/10 hover:bg-white/20 p-3 rounded-xl transition-colors text-sm font-medium">
                <Mail className="w-4 h-4 text-[#FFD700]" /> support@ditmur.com
              </a>
              <a href="tel:+2348000000000" className="flex items-center gap-3 bg-white/10 hover:bg-white/20 p-3 rounded-xl transition-colors text-sm font-medium">
                <PhoneCall className="w-4 h-4 text-[#FFD700]" /> +234 (0) 800 000 0000
              </a>
            </div>
          </div>
        </div>

        {/* RIGHT COL: FAQs */}
        <div className="lg:col-span-2 space-y-6">
          {faqs.map((category, idx) => (
            <div key={idx} className="bg-white rounded-2xl border border-slate-200 shadow-sm overflow-hidden">
              <div className="p-5 border-b border-slate-100 bg-slate-50">
                <h3 className="font-bold text-slate-900">{category.category}</h3>
              </div>
              <div className="divide-y divide-slate-100">
                {category.items.map((item, itemIdx) => {
                  // Simple search filter
                  if (searchQuery && !item.q.toLowerCase().includes(searchQuery.toLowerCase()) && !item.a.toLowerCase().includes(searchQuery.toLowerCase())) {
                    return null;
                  }
                  
                  return (
                    <div key={itemIdx} className="p-5 hover:bg-slate-50/50 transition-colors">
                      <h4 className="font-bold text-slate-800 text-sm mb-2">{item.q}</h4>
                      <p className="text-sm text-slate-600 leading-relaxed">{item.a}</p>
                    </div>
                  );
                })}
              </div>
            </div>
          ))}
        </div>

      </div>
    </div>
  );
}
